repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        name: ruff lint
        args: ["--fix"]
        files: ^si/
      - id: ruff
        name: ruff lint preview
        args: ["--fix", "--preview", "--select=NPY201"]
        files: ^si/
      - id: ruff
        name: ruff lint doc, tutorials, tests and examples
        # D103: missing docstring in public function
        # D400: docstring first line must end with period
        args: ["--ignore=D103,D400", "--fix"]
        files: ^docs/|^examples/^test/
      - id: ruff-format
        files: ^si/|^docs/|^examples/|

  # Codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        files: ^si/|^docs/|^examples/
        types_or: [python, bib, rst, inc]
        args: [
          "--ignore-words",
          "ignore-words.txt",
        ]

  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        # args: [--strict]
